### ISSUE TITLE
Error executing query on NeuroArch

### ISSUE THREAD

**Issue by urnotlcxz** [FlyBrainLab/FlyBrainLab#10]
I use the hemibrain datasets in my workspace, but when I write the query in _Write Query_   it doesn't have any results or graphics. Then I try the code in Tutorials Part 1(b): 
```
my_client = fbl.get_client()
res = my_client.executeNLPquery('show alpha_beta_kc')
```
It shows errors:

```
> [FBL NLP 2022-08-01 12:19:36,032] NLP successfully parsed query.
> ---------------------------------------------------------------------------
> FlyBrainLabNAserverException              Traceback (most recent call last)
> <ipython-input-19-cbe317317ce1> in <module>
> ----> 1 res = my_client.executeNLPquery('show APL')
> 
> ~/miniconda/envs/ffbo/lib/python3.7/site-packages/flybrainlab/Client.py in executeNLPquery(self, query, language, uri, queryID, returnNAOutput)
>    1465                 self.compiled = False
>    1466                 res = self.executeNAquery(
> -> 1467                     resNA, queryID=queryID, threshold=self.query_threshold
>    1468                 )
>    1469                 if 'show ' in query or 'add ' in query or 'remove ' in query:
> 
> ~/miniconda/envs/ffbo/lib/python3.7/site-packages/flybrainlab/Client.py in executeNAquery(self, task, language, uri, queryID, progressive, threshold, temp)
>    1648             self.active_na_queries.pop(queryID)
>    1649             self.NLP_result.clear_cmd()
> -> 1650             raise FlyBrainLabNAserverException(res['info']['error'])
>    1651         self.last_NAquery_result = self.active_na_queries[queryID]
>    1652         return self.active_na_queries.pop(queryID)
> 
> FlyBrainLabNAserverException: Error executing query on NeuroArch
```
Also,my Neu3D-1::Untitled.ipynb is black without any neurons or some visual graphics.

Thanks!

**Comment by yiyin** [comment]
Hi @urnotlcxz,

For the Hemibrain dataset, Neu3D window should have the neuropils displayed once you are connected to the server.
Can you please check which version of flybrainlab you are using? 
```
import flybrainlab
print(flybrainlab.__version__)
```

**Comment by urnotlcxz** [comment]
Hi @yiyin,
My flybrainlab version is 1.1.7. And I use the Docker Installation. 
Thanks!

**Comment by yiyin** [comment]
Did you get any error message (typically it will come up on the lower right) when creating the Hemibrain workspace? 

When you start the container, it will first ask you to download the datasets for the database, like the following:
```
Download datasets to /home/ffbo/orientdb? (Y/n) y
Download Hemibrain v1.2? (y/N) y
...
```
You will need to explicitly `y` to the second question (and any other dataset you want to download).

Did you encounter any error when doing the above? If the database is not loaded correctly, the servers will not be created and you won't be able to connect to the hemibrain dataset.

By the way, you can also try the latest docker image that I just uploaded. Either
```
docker pull fruitflybrain/fbl:latest
```
or
```
docker pull fruitflybrain/fbl:1.1.9
```
