### ISSUE TITLE
Run scripts appears to be missing from dev install

### ISSUE THREAD

**Issue by Cpruce** [FlyBrainLab/FlyBrainLab#11]
The [run_scripts repo](https://github.com/FlyBrainLab/run_scripts) appears to be missing from the [dev install script](https://github.com/FlyBrainLab/FlyBrainLab/blob/master/fbl_full_installation_ubuntu_develop.sh). It is referenced in the file, resulting in an error if nothing is done about it. Using the non-dev install script as an example, cloning the repo appears to be missing.

I'll close this if it is intentional or submit a PR if not! Thanks :)

**Comment by yiyin** [comment]
Thanks! Yes, it's been fixed earlier today https://github.com/FlyBrainLab/FlyBrainLab/commit/51102912d420af1ee4ed09357adc5b30bbe1870e.

**Comment by Cpruce** [comment]
Awesome, thanks! 😄
