### ISSUE TITLE
Front End using conda - installing nxt_gem.git throws an error

### ISSUE THREAD

**Issue by sgarnell** [FlyBrainLab/FlyBrainLab#13]
Installing the front end using miniconda was working just fine last week. However, now when I install it this week, I get a strange error when the install hits the nxt_gem package, see below the output provided.

Also, in my attempts to fix this, I tried updating my pip and the setuptools packages based on internet comments I saw. Didn't help.

****************************error in console ****************************

Collecting git+https://github.com/jernsting/nxt_gem.git
  Cloning https://github.com/jernsting/nxt_gem.git to c:\users\saul\appdata\local\temp\pip-req-build-pwt3nfir
  Running command git clone --filter=blob:none --quiet https://github.com/jernsting/nxt_gem.git 'C:\Users\saul\AppData\Local\Temp\pip-req-build-pwt3nfir'
  Resolved https://github.com/jernsting/nxt_gem.git to commit 9f1ba7de35e87cb3521387cd393306a3fef5f79c
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      C:\Users\saul\miniconda3\envs\flybrainlab\lib\site-packages\setuptools\_distutils\dist.py:265: UserWarning: Unknown distribution option: 'pbr'
        warnings.warn(msg)
      error: Multiple top-level packages discovered in a flat-layout: ['gem', 'images'].

      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.

      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:

      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names

      To find more information, look for "package discovery" on setuptools docs.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

**Comment by yiyin** [comment]
Fixed the `nxt_gem` dependency in 67857ca4.
Thanks for reporting!
