### ISSUE TITLE
Certtificate Expired

### ISSUE THREAD

**Issue by sgarnell** [FlyBrainLab/FlyBrainLab#16]
When I start my Hemibrain session on the docker version of flybrainLab, I get this error inside the NeuGFX widget:
I think you need to renew the certificates again?
Thanks!

Websites prove their identity via certificates, which are valid for a set time period. The certificate for ffbolab.neurogfx.fruitflybrain.org expired on 4/2/2024.
 
Error code: [SEC_ERROR_EXPIRED_CERTIFICATE](about:certerror?e=nssBadCert&u=https%3A//ffbolab.neurogfx.fruitflybrain.org/&c=UTF-8&d=%20#certificateErrorDebugInformation)
 
[View Certificate](javascript:void(0))

I
![Screenshot 2024-04-02 213533](https://github.com/FlyBrainLab/FlyBrainLab/assets/79667791/570df7d7-c5bb-4b95-90f7-cf91b1892f9e)

**Comment by yiyin** [comment]
Thanks. Updated.
