### ISSUE TITLE
Insecure HTTPs request - Refusing to connect to processor

### ISSUE THREAD

**Issue by ShashShukla** [FlyBrainLab/FlyBrainLab#9]
I ran the full installation script on Ubuntu 18.04 LTS, with all the prerequisite packages in place. The installation script did not throw any error. I then ran "start.sh" to succesfully open FBL (a popup stated that the backend packages are configured correctly). 

However, upon trying to connect a Neu3D widget to a dataset (I tried Hemibrain, Flycircuit, Larva and Medulla) I get the following error:

`/home/shashwat/anaconda3/envs/ffbo/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/home/shashwat/anaconda3/envs/ffbo/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

---------------------------------------------------------------------------
ConnectionRefusedError                    Traceback (most recent call last)
<ipython-input-2-941f19ecc10c> in <module>
     13 dataset='hemibrain',
     14 realm=u'realm1',
---> 15   ca_cert_file="isrgrootx1.pem",)
     16   fbl.client_manager.add_client('client-Neu3D-1-fa2629de-8418-415a-bc22-912d6d02109c', _client, client_widgets=['Neu3D-1-fa2629de-8418-415a-bc22-912d6d02109c'])
     17 else:

~/anaconda3/envs/ffbo/lib/python3.7/site-packages/flybrainlab/Client.py in __init__(self, ssl, debug, authentication, user, secret, custom_salt, url, realm, ca_cert_file, intermediate_cert_file, FFBOLabcomm, FBLcomm, legacy, initialize_client, name, species, use_config, custom_config, widgets, dataset, log_level)
    639             self.legacy = legacy
    640             self.dataset = dataset
--> 641             self.init_client(ssl, user, secret, custom_salt, url, ssl_con, legacy)
    642             self.findServerIDs(dataset)  # Get current server IDs
    643             self.connected = True

~/anaconda3/envs/ffbo/lib/python3.7/site-packages/flybrainlab/Client.py in init_client(self, ssl, user, secret, custom_salt, url, ssl_con, legacy)
    805             )  # Initialize the communication right now!
    806         else:
--> 807             FBLClient.run(url=url, authmethods=[u'wampcra'], authid=user)
    808 
    809         setProtocolOptions(FBLClient._async_session._transport,

~/anaconda3/envs/ffbo/lib/python3.7/site-packages/autobahn_sync/core.py in run(self, url, realm, authmethods, authid, authrole, authextra, blocking, callback, **kwargs)
    105         self._bootstrap(blocking, url=url, realm=realm,
    106                 authmethods=authmethods, authid=authid, authrole=authrole,
--> 107                 authextra=authextra, **kwargs)
    108         if callback:
    109             callback()

~/anaconda3/envs/ffbo/lib/python3.7/site-packages/autobahn_sync/core.py in _bootstrap(self, blocking, **kwargs)
    177 
    178         logger.debug('[MainThread] call bootstrap')
--> 179         start_runner()
    180         logger.debug('[MainThread] call decorated register/subscribe')
    181         for cb in self._on_running_callbacks:

~/anaconda3/envs/ffbo/lib/python3.7/site-packages/crochet/_eventloop.py in wrapper(function, _, args, kwargs)
    508                 eventual_result = run()
    509                 try:
--> 510                     return eventual_result.wait(timeout)
    511                 except TimeoutError:
    512                     eventual_result.cancel()

~/anaconda3/envs/ffbo/lib/python3.7/site-packages/crochet/_eventloop.py in wait(self, timeout)
    239         result = self._result(timeout)
    240         if isinstance(result, Failure):
--> 241             result.raiseException()
    242         return result
    243 

~/anaconda3/envs/ffbo/lib/python3.7/site-packages/twisted/python/failure.py in raiseException(self)
    473         # Python 3
    474         def raiseException(self):
--> 475             raise self.value.with_traceback(self.tb)
    476 
    477     else:

ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.`

I am thus unable to use FBL with Neuroarch as intended. 
Thanks!

**Comment by yiyin** [comment]
Can you check if the other tmux sessions are still alive and/or have error? Particularly the session with name processor.

Another part to check is the processor configuration: https://github.com/FlyBrainLab/FlyBrainLab/wiki/Installation. What are the IP for each dataset?

**Comment by ShashShukla** [comment]
Running `tmux ls` gives:
```
db: 1 windows (created Wed May  5 11:30:54 2021) [80x24]
neuroarch_flycircuit: 1 windows (created Wed May  5 11:31:14 2021) [80x24]
neuroarch_hemibrain: 1 windows (created Wed May  5 11:31:14 2021) [80x24]
neuroarch_l1em: 1 windows (created Wed May  5 11:31:14 2021) [80x24]
neuroarch_medulla: 1 windows (created Wed May  5 11:31:14 2021) [80x24]
neurokernel: 1 windows (created Wed May  5 11:31:14 2021) [80x24]
nlp_flycircuit: 1 windows (created Wed May  5 11:31:14 2021) [80x24]
nlp_hemibrain: 1 windows (created Wed May  5 11:31:14 2021) [80x24]
nlp_l1em: 1 windows (created Wed May  5 11:31:14 2021) [80x24]
nlp_medulla: 1 windows (created Wed May  5 11:31:14 2021) [80x24]
```
Thus there does not seem to be a session named "processor". 

Regarding processor configuration, the settings seem to be identical to the link you shared, with the following exceptions: 
1. The IP address is set to `localhost:8081`. 
2. SSL is set to `false` (this should not be relevant as FBL should be accessing a local database). 

Note that switching authentication off in the server settings also does not work.

**Comment by yiyin** [comment]
The processor is down so there is no way you can connect to it.
The reason it fails is probably that was the time I was updating the installation scripts. The repo for execution scripts was updated a day earlier and becomes incompatible with the older install script.
If you pull the latest, it should work fine.

**Comment by ShashShukla** [comment]
Thank you, using the new installation script solves this issue.
